force-app/main/default/objects/Eclipse__c/Eclipse__c.object-meta.xml
<CustomObject>
    <description>This is a generic template for Custom Object.  With this template, you may adjust the default elements and values and add new elements and values.</description>
    <label>Eclipse</label>
    <nameField>
        <label>Eclipse Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Eclipses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Eclipse__c/fields/Policy_ID__c.field-meta.xml
<CustomField>
    <fullName>Policy_ID__c</fullName>
    <label>Policy ID</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/BatchToUpdatePolicyId.cls
global class BatchToUpdatePolicyId implements Database.batchable<sObject>{

         
     global Database.QueryLocator start(Database.BatchableContext BC){
      
        String query = 'SELECT Id,Name,Policy_ID__c FROM Eclipse__c';
        return Database.getQueryLocator(query);

     }
     global void execute(Database.BatchableContext BC, List<Eclipse__c> scope){
        
        //List of accounts to update
        List<Eclipse__c> eclToUpdateList =  new List<Eclipse__c>();
         try{
            for(Eclipse__c ec: scope){
               ec.Policy_ID__c = ec.Name+'_1';
               
               eclToUpdateList.add(ec);
               
             }
             
              //Checking if the list is empty
              if(!eclToUpdateList.isEmpty()){
                update eclToUpdateList;
              }
              
                            
          }
          
         // Catching the exception
        catch(Exception ex) {
            
            System.debug('Error:'+ex.getMessage());
        }  
        
       } 
       
       global void finish(Database.BatchableContext BC){
        
       }

}