force-app/main/default/objects/Eclipse__c/Eclipse__c.object-meta.xml
<CustomObject>
    <description>This is a generic template for Custom Object.  With this template, you may adjust the default elements and values and add new elements and values.</description>
    <label>Eclipse</label>
    <nameField>
        <label>Eclipse Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Eclipses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Eclipse__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Eclipses</relationshipLabel>
    <relationshipName>Eclipses</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Eclipse__c/fields/Relationship__c.field-meta.xml
<CustomField>
    <fullName>Relationship__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Relationship</label>
    <referenceTo>Relationship__c</referenceTo>
    <relationshipLabel>Eclipses</relationshipLabel>
    <relationshipName>Eclipses</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Relationship__c/Relationship__c.object-meta.xml
<CustomObject>
    <label>Relationship</label>
    <nameField>
        <label>Relationship Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Relationships</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/classes/CustomExtensionController.cls
public with sharing class CustomExtensionController {  
    
    public Eclipse__c ecp{get;set;} 
    public Eclipse__c ecret{get;set;} 
    
    public Account account{get;set;}
    ApexPages.StandardController sController;  
    
    public CustomExtensionController (ApexPages.StandardController controller) {  
        sController = controller;  
        ecp = (Eclipse__c)controller.getRecord();  
    }  
    
    public PageReference saveCustom() {  
        
        // Custom Save code here...  
        
        try{
        	PageReference pr = sController.save();
            Id recId = pr.getUrl().substring(1);
            
            ecret = [select id,name,Relationship__c,Account__c,Account__r.Name from Eclipse__c where Account__c!=null AND Id=:recId   limit 1];
        	
             
            
            ecret.Name=ecret.Account__r.Name;
            update ecret;
            
            return pr; 
        }Catch(Exception e){
            e.getMessage();
            
             return null; 
        }
        
        
        
        
        
        // Alternatively, could return a PR to the view page.  
        //pageReference pv = sController.view();  
        
    }  
}