force-app/main/default/objects/NWD_Citizen__c/NWD_Citizen__c.object-meta.xml
<CustomObject>
    <label>Citizen</label>
    <nameField>
        <label>Citizen Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Citizens</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/NWD_Citizen__c/fields/Age__c.field-meta.xml
<CustomField>
    <fullName>Age__c</fullName>
    <formula>IF(YEAR(TODAY()) == YEAR(DOB__c),
0,
IF(MONTH(TODAY()) == MONTH(DOB__c),
IF(DAY(TODAY()) &lt; DAY(DOB__c),
(YEAR(TODAY()) - YEAR(DOB__c) -1),
(YEAR(TODAY()) - YEAR(DOB__c))
),
IF(MONTH(TODAY()) &lt; MONTH(DOB__c),
(YEAR(TODAY()) - YEAR(DOB__c) -1),
(YEAR(TODAY()) - YEAR(DOB__c))
)
)
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Age</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/NWD_Citizen__c/fields/Relationship_To_Houshold__c.field-meta.xml
<CustomField>
    <fullName>Relationship_To_Houshold__c</fullName>
    <label>Relationship To Houshold</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Husband</fullName>
            </value>
            <value>
                <fullName>Wife</fullName>
            </value>
            <value>
                <fullName>Son</fullName>
            </value>
            <value>
                <fullName>Daughter</fullName>
            </value>
            <value>
                <fullName>Father</fullName>
            </value>
            <value>
                <fullName>Mother</fullName>
            </value>
            <value>
                <fullName>Sel</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/NWD_HouseholdController.cls
public class NWD_HouseholdController {
    
    @AuraEnabled
    public static List<NWD_Citizen__c> getFMembers() {
    return [SELECT Id, Name, First_Name__c, Last_Name__c, Age__c, Gender__c, Relationship_To_Houshold__c FROM NWD_Citizen__c ORDER BY CreatedDate DESC];
      }
    
    @AuraEnabled
    public static NWD_Citizen__c saveCitizen(NWD_Citizen__c cit) {

    upsert cit;
    return cit;
    }

}