force-app/main/default/objects/ClientBenefit__c/ClientBenefit__c.object-meta.xml
<CustomObject>
    <label>Citizen Benefit</label>
    <nameField>
        <label>Citizen Benefit Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Citizen Benefits</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/ClientBenefit__c/fields/Agency__c.field-meta.xml
<CustomField>
    <fullName>Agency__c</fullName>
    <label>Agency</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Welfare and Supportive Services(DWSS)</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ClientBenefit__c/fields/Citizen__c.field-meta.xml
<CustomField>
    <fullName>Citizen__c</fullName>
    <label>Citizen</label>
    <referenceTo>NWD_Citizen__c</referenceTo>
    <relationshipLabel>Citizen Benefits</relationshipLabel>
    <relationshipName>Citizen_Benefits</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/ClientBenefit__c/fields/Program__c.field-meta.xml
<CustomField>
    <fullName>Program__c</fullName>
    <label>Program</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Food Assistance</fullName>
            </value>
            <value>
                <fullName>Cash Assistance</fullName>
            </value>
            <value>
                <fullName>Medical Assistance</fullName>
            </value>
            <value>
                <fullName>Education Assistance</fullName>
            </value>
            <value>
                <fullName>Workforce Assistance</fullName>
            </value>
            <value>
                <fullName>ChildCare Assistance</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/NWD_Citizen__c/NWD_Citizen__c.object-meta.xml
<CustomObject>
    <label>Citizen</label>
    <nameField>
        <label>Citizen Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Citizens</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/NWD_MyBenefitsController.cls
public class NWD_MyBenefitsController {
@AuraEnabled
  /*public static List<ClientBenefit__c> getBenefits() {
   // return [SELECT Id, Name, First_Name__c, Last_Name__c FROM NWD_Citizen__c ORDER BY createdDate ASC];
      //system.debug([SELECT Id, Name, First_Name__c, Last_Name__c FROM NWD_Citizen__c ORDER BY createdDate ASC]);
      return [SELECT Id, Name,  citizen__r.Name, Agency__c, Program__c, Start_Date__c, End_Date__c FROM ClientBenefit__c];
  }*/
    
    public static List<ClientBenefit__c> getBenefits(String sortField, boolean isAsc) {
    String query = 'SELECT Id, Name, Citizen__r.Name, Agency__c, Program__c, Start_Date__c, End_Date__c';
        query += ' FROM ClientBenefit__c';
       if (sortField != '') {
         query += ' order by ' + sortField;
 
    // if isAsc is equal tp ture then set 'asc' order otherwise set 'desc' order.
         if (isAsc) {
            query += ' asc';
         } else {
            query += ' desc';
         }
      }
      list <ClientBenefit__c> citList;
        try {
         system.debug('The query is' + query);
         citList = Database.query(query);
         List <ClientBenefit__c> retCitList = new List <ClientBenefit__c>();
 
         for (ClientBenefit__c cit: citList) {
            retCitList.add(cit);
          }
            system.debug('List in apex is '+retCitList);
         return retCitList;
      } 
      catch (Exception ex) {
         // for handle Exception
         return null;
      }
  }
}