force-app/main/default/objects/Campaign_Relationship_Association__c/Campaign_Relationship_Association__c.object-meta.xml
<CustomObject>
    <label>Campaign Relationship Association</label>
    <nameField>
        <label>Campaign Relationship Association Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Campaign Relationship Associations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Campaign_Relationship_Association__c/fields/Campaign__c.field-meta.xml
<CustomField>
    <fullName>Campaign__c</fullName>
    <label>Campaign</label>
    <referenceTo>Campaign</referenceTo>
    <relationshipLabel>Campaign Relationship Associations</relationshipLabel>
    <relationshipName>Campaign_Relationship_Associations</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Campaign_Relationship_Association__c/fields/Relationship__c.field-meta.xml
<CustomField>
    <fullName>Relationship__c</fullName>
    <label>Relationship</label>
    <referenceTo>Relationship__c</referenceTo>
    <relationshipLabel>Campaign Relationship Associations</relationshipLabel>
    <relationshipName>Campaign_Relationship_Associations</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Relationship__c/Relationship__c.object-meta.xml
<CustomObject>
    <label>Relationship</label>
    <nameField>
        <label>Relationship Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Relationships</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Relationship__c/fields/Primary_Relationship_Contact__c.field-meta.xml
<CustomField>
    <fullName>Primary_Relationship_Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Primary Relationship Contact</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Relationships</relationshipLabel>
    <relationshipName>Relationships</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/CRM_CampaignAddselected.cls
global without sharing class CRM_CampaignAddselected {

    public CRM_CampaignAddselected(ApexPages.StandardController controller) {
      }
    public static void AddSelectedToCampaign(List<Relationship__c> relLst, Campaign cmp) {

        List<Campaign_Relationship_Association__c> craLst = new List<Campaign_Relationship_Association__c>();
        List<CampaignMember> cmLst = new List<CampaignMember>();
        Set<Id> AccIds = new Set<Id>();

        for (Relationship__c r : relLst) {
            Campaign_Relationship_Association__c cra = new Campaign_Relationship_Association__c(Relationship__c = r.id, Campaign__c = cmp.id);
            craLst.add(cra);
            AccIds.add(r.Primary_Relationship_Contact__c);
        }

        List<Contact> conLst = [SELECT Id FROM Contact WHERE AccountId IN :AccIds AND Id NOT IN (SELECT ContactId FROM CampaignMember WHERE CampaignId = :cmp.Id)];
        for (Contact c : conLst) {
            CampaignMember newCm = new CampaignMember(CampaignId = cmp.Id, ContactId = c.Id);
            cmLst.add(newCm);
        }

        insert cmLst;
        insert craLst;
    }
    public static void AddSelectToCam(List<Relationship__c> relLst, Campaign cmp) {

        List<Campaign_Relationship_Association__c> craLst = new List<Campaign_Relationship_Association__c>();
        List<CampaignMember> cmLst = new List<CampaignMember>();
        Set<Id> AccIds = new Set<Id>();

        for (Relationship__c r : relLst) {
            Campaign_Relationship_Association__c cra = new Campaign_Relationship_Association__c(Relationship__c = r.id, Campaign__c = cmp.id);
            craLst.add(cra);
            AccIds.add(r.Primary_Relationship_Contact__c);
        }

        List<Contact> conLst = [SELECT Id FROM Contact WHERE AccountId IN :AccIds AND Id NOT IN (SELECT ContactId FROM CampaignMember WHERE CampaignId = :cmp.Id)];
        for (Contact c : conLst) {
            CampaignMember newCm = new CampaignMember(CampaignId = cmp.Id, ContactId = c.Id);
            cmLst.add(newCm);
        }

        insert cmLst;
        insert craLst;
    }
    public void star() {
        Set<Id> AccIds1 = new Set<Id>();



    }
    static webService String DeleteRelationshipFromCampaign(List<Id> records) {
        List<Campaign_Relationship_Association__c> recToDelete = [SELECT id,Campaign__c,Relationship__c,Relationship__r.Primary_Relationship_Contact__c FROM Campaign_Relationship_Association__c WHERE id = :records];
        Set<Id> AccIds = new Set<Id>();

        for (Campaign_Relationship_Association__c cra : recToDelete) {
            AccIds.add(cra.Relationship__r.Primary_Relationship_Contact__c);

        }
        List<CampaignMember> cmLstToDelete = [SELECT Id,ContactId FROM CampaignMember WHERE ContactId IN (SELECT Id FROM Contact WHERE AccountId IN :AccIds)];
        //return 'CampaignMembers to Delete:'+ cmLstToDelete+'\n ####### \n Junstion records to Delete: '+recToDelete ;
        delete recToDelete;
        delete cmLstToDelete;

        return 'Records will be deleted in 2 secs';
    }
}